### ISSUE TITLE
Player "quick stats"

### ISSUE THREAD

**Issue by intellibruce** [Intellipharm/oh-hell#5]
Under each player’s name it would be cool to have some basic “quick stats”.

This could exist as the following three elements:

•	Amount of accurate bids vs rounds (Example - 7 from 10)
•	Bid percentage (Example - 75%)
•	“Perfect Game” - If the player is on 100% it says “Perfect Game”. Doesn't need to say the bids vs rounds / percentage etc.

**Comment by Tim-Intellipharm** [comment]
@intellibruce Isn't this what the charts are showing?

**Comment by intellibruce** [comment]
Kind of. The charts are great, but this would just display the exact figure under the name to complement the charts with a simple accurate bid amount and percentage as a faster reference.   

**Sally**

2/4 (50%)
**Bob**

4/4 (100%)

Perfect Game!

No changes to the charts required, this is just a nice to have.
